### ISSUE TITLE
App.Post.find() doesn't work ?

### ISSUE THREAD

**Issue by abhayathapa** [charlieridley/ember-typeahead#2]
```
App.PostsRoute = Ember.Route.extend
   model: ->
     App.Post.find()
#handlebar
{{type-ahead data=content name="type" selection=myColour}}
```

If I use `[ Ember.Object.create(type: "Red"), Ember.Object.create(type: "Reddi") ]` in model it works fine. How to make it work for App.Post.find() ? 

Any help would be appreciated.

**Comment by charlieridley** [comment]
Are you using ember-data?

**Comment by abhayathapa** [comment]
Yes ember-data with fixtures.

**Comment by charlieridley** [comment]
What version of ED? The latest version you are supposed to query the store like this:

```
App.PostsRoute = Ember.Route.extend
   model: ->
     @store.find("post")
```

That will return a promise which should work.

**Comment by abhayathapa** [comment]
I'm using ember-rails. Gemfile lock shows ember-data-source (0.14).  I was already using @store. Textbox doesn't populate typeahead this way.Only when I use '[ Ember.Object.create(type: "Red"), Ember.Object.create(type: "Reddi") ]' it gets typeahead. 

Any help would be highly appreciated.

**Comment by charlieridley** [comment]
I'm not sure 0.14 returns a promise from the find method. If you can upgrade to 1.0beta you might find it works.

**Comment by abhayathapa** [comment]
Actually I was using older ember-data. As I upgraded both ember-data and emberjs to latest beta I got error for typeahead error because it was not Ember.Set. Now with EmberData(1.0.0-beta.5+pre.69cb8b87) and emberjs 1.2 its working as expected.

Thanks for help
